In [ ]:
# google drive에 연결 (MyDrive에 기쁨코인이 없다면 기쁨코인 폴더 우클릭->"드라이브 바로가기 추가" 클릭)
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
# 로드할 파일의 경로
path ='/content/drive/MyDrive/기쁨코인/dataset/서울시 대형학원 정보.csv'

data = pd.read_csv(path, encoding='cp949')
data.columns

Index(['개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자', '영업상태코드', '영업상태명', '상세영업상태코드',
       '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자', '전화번호', '소재지면적',
       '소재지우편번호', '지번주소', '도로명주소', '도로명우편번호', '사업장명', '최종수정일자', '데이터갱신구분',
       '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)', '문화체육업종명', '공사립구분명',
       '보험가입여부코드', '지도자수', '건축물동수', '건축물연면적', '회원모집총인원', '세부업종명', '법인명'],
      dtype='object')

In [ ]:
data.dtypes

개방자치단체코드      int64
관리번호         object
인허가일자         int64
인허가취소일자     float64
영업상태코드        int64
영업상태명        object
상세영업상태코드      int64
상세영업상태명      object
폐업일자        float64
휴업시작일자      float64
휴업종료일자      float64
재개업일자       float64
전화번호         object
소재지면적       float64
소재지우편번호     float64
지번주소         object
도로명주소        object
도로명우편번호     float64
사업장명         object
최종수정일자        int64
데이터갱신구분      object
데이터갱신일자      object
업태구분명       float64
좌표정보(X)     float64
좌표정보(Y)     float64
문화체육업종명      object
공사립구분명       object
보험가입여부코드     object
지도자수        float64
건축물동수       float64
건축물연면적      float64
회원모집총인원     float64
세부업종명       float64
법인명         float64
dtype: object

In [ ]:
data['인허가일자1'] = data['인허가일자']/ 10000

In [ ]:
data15 = data.loc[data['인허가일자1'] < 2016]
data16 = data.loc[data['인허가일자1'] < 2017]
data17 = data.loc[data['인허가일자1'] < 2018]

data15 = data15.drop('인허가일자1', axis = 1)
data16 = data16.drop('인허가일자1', axis = 1)
data17 = data17.drop('인허가일자1', axis = 1)

In [ ]:
data['폐업일자1'] = data['폐업일자']/ 10000

In [ ]:
data['폐업일자1'] = data['폐업일자1'].fillna(3000)

In [ ]:
data15 = data15.loc[data['폐업일자1'] > 2015]
data16 = data16.loc[data['폐업일자1'] > 2016]
data17 = data17.loc[data['폐업일자1'] > 2017]

In [ ]:
# 저장할 csv 파일 이름 및 경로 설정
data15.to_csv('/content/drive/MyDrive/기쁨코인/dataset/체력단련장_2015.csv', encoding='utf-8')
data16.to_csv('/content/drive/MyDrive/기쁨코인/dataset/체력단련장_2016.csv', encoding='utf-8')
data17.to_csv('/content/drive/MyDrive/기쁨코인/dataset/체력단련장_2017.csv', encoding='utf-8')

In [ ]:
len(data15)

804

In [ ]:
len(data16)

756

In [ ]:
len(data17)

717

In [ ]:
path ='/content/drive/MyDrive/기쁨코인/dataset/서울시 공연장 인허가 정보.csv'
data = pd.read_csv(path, encoding='cp949')

data.loc[:, ['좌표정보(X)', '좌표정보(Y)']]

            좌표정보(X)        좌표정보(Y)
0     197804.357783  452216.539275
1     195240.580598  459453.395212
2               NaN            NaN
3     204013.181170  447200.862869
4     200386.709770  454046.197498
...             ...            ...
1302  210992.497270  447372.617183
1303  212562.756068  448215.522397
1304  200221.159827  453443.564355
1305  200221.159827  453443.564355
1306  200221.159827  453443.564355

[1307 rows x 2 columns]

In [ ]:
import pandas as pd
import os

def data_cleansing_1(name):
    # 로드할 파일의 경로
    path ='/content/drive/MyDrive/기쁨코인/dataset/서울시 '+name+' 인허가 정보.csv'
    data = pd.read_csv(path, encoding='cp949')

    # 모든 테이블이 똑같이 생겼음을 이용해서 2015, 2016, 2017년에 존재했던 가게들을 남게끔 처리합니다
    data['인허가일자1'] = data['인허가일자']/ 10000
    data['폐업일자1'] = data['폐업일자']/ 10000

    data['폐업일자1'] = data['폐업일자1'].fillna(3000)

    data15 = data.loc[data['인허가일자1'] < 2016]
    data16 = data.loc[data['인허가일자1'] < 2017]
    data17 = data.loc[data['인허가일자1'] < 2018]

    data15 = data15.drop('인허가일자1', axis = 1)
    data16 = data16.drop('인허가일자1', axis = 1)
    data17 = data17.drop('인허가일자1', axis = 1)

    data15 = data15.loc[data['폐업일자1'] > 2015]
    data16 = data16.loc[data['폐업일자1'] > 2016]
    data17 = data17.loc[data['폐업일자1'] > 2017]

    # 저장할 csv 파일 이름 및 경로 설정
    os.mkdir('/content/drive/MyDrive/기쁨코인/dataset/'+name)
    data15.to_csv('/content/drive/MyDrive/기쁨코인/dataset/'+name+'/'+name+'_2015.csv', encoding='utf-8')
    data16.to_csv('/content/drive/MyDrive/기쁨코인/dataset/'+name+'/'+name+'_2016.csv', encoding='utf-8')
    data17.to_csv('/content/drive/MyDrive/기쁨코인/dataset/'+name+'/'+name+'_2017.csv', encoding='utf-8')

data_cleansing_1('당구장업')
data_cleansing_1('골프연습장업')
data_cleansing_1('인터넷컴퓨터게임시설제공업')
data_cleansing_1('일반게임제공업')
data_cleansing_1('유원시설업(기타)')