In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import numpy as np
import pandas as pd

In [3]:
path = "/content/drive/MyDrive/기쁨코인/dataset/table/table_2015.csv"

In [4]:
table_2015 = pd.read_csv(path).drop("Unnamed: 0", axis=1) # 열어보니 쓸데없는 행이 한개 있길래 지웁니다

In [5]:
table_2015

,building t,case num,address,Latitude,Longitude,size,appraiser,lowest,success,bid_date,...,병원_0.8km,병원_1km,대규모점포_0.4km,대규모점포_0.6km,대규모점포_0.8km,대규모점포_1km,관광극장유흥업_0.4km,관광극장유흥업_0.6km,관광극장유흥업_0.8km,관광극장유흥업_1km
0,오피스텔,2015 타경 12810,서울 강남구 대치동 889-47 비동 3층 317호,37.503835,127.050223,건물 38.71㎡(11.71평) / 대지권 7.75㎡(2.34평),202000000,161600000,191100000.0,2015/12/29,...,6,9,1,1,7,10,0,0,0,0
1,근린상가,2015 타경 179,서울 성동구 성수동2가 351 2층 203호,37.537619,127.051455,건물 61.25㎡(18.53평) / 대지권 48.18㎡(14.57평),425000000,217600000,235820000.0,2015/12/28,...,0,3,2,2,3,4,0,0,0,0
2,근린상가,2015 타경 4065,서울 광진구 구의동 546-4 테크노-마트21 5층 비066호,37.534937,127.095709,건물 11.07㎡(3.35평) / 대지권 2.93㎡(0.89평),52000000,41600000,NaN,2015/12/28,...,0,0,3,6,8,8,0,0,0,0
3,근린상가,2015 타경 5668,서울 동대문구 용두동 788 한방천하-용두동포스빌 2층 273호,37.577807,127.036898,건물 6.6㎡(2평) / 대지권 1.79㎡(0.54평),32000000,20480000,21289000.0,2015/12/28,...,5,8,7,9,12,15,0,0,0,0
4,근린상가,2015 타경 5976,서울 성동구 옥수동 100 옥수하이츠 상가동 1층 112호,37.540118,127.016386,건물 27㎡(8.17평) / 대지권 24.72㎡(7.48평),130000000,130000000,151167100.0,2015/12/28,...,0,0,1,2,2,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107,오피스텔,2014 타경 14320,서울 노원구 월계동 366-3 2층 201호,37.624881,127.060288,건물 33.75㎡(10.21평) / 대지권 13.58㎡(4.11평),125000000,100000000,103700000.0,2015/01/12,...,0,0,3,3,3,5,0,0,0,0
1108,오피스텔,2014 타경 4184,서울 영등포구 양평동4가 23-7 2층 207호,37.535671,126.894746,건물 32.21㎡(9.74평) / 대지권 11.51㎡(3.48평),205000000,164000000,185500000.0,2015/01/07,...,2,7,1,1,1,4,0,0,0,0
1109,근린시설,2014 타경 3522,서울 성동구 마장동 767-27,37.568139,127.045086,건물 145.77㎡(44.1평) / 토지 99.8㎡(30.19평) / 제시외 71.2 ㎡,406059600,259878000,339555000.0,2015/01/05,...,1,5,0,1,3,5,0,0,0,0
1110,오피스텔,2014 타경 5955,서울 송파구 잠실동 175-1 10층 1005호,37.510752,127.078933,건물 33.92㎡(10.26평) / 대지권 8.26㎡(2.5평),160000000,128000000,141000000.0,2015/01/05,...,1,1,1,2,2,3,2,2,2,2
1111,근린상가,2014 타경 7623,서울 송파구 가락동 75 2층 201 호,37.496290,127.120726,건물 245.44㎡(74.25평),230000000,230000000,NaN,2015/07/06,...,7,8,0,3,4,6,0,0,0,0

In [6]:
table_2015['address'][2].split()

['서울', '광진구', '구의동', '546-4', '테크노-마트21', '5층', '비066호']

In [7]:
gu = []
for i in range(len(table_2015)):
    new = table_2015['address'][i].split()[1]
    if new in gu: continue
    gu.append(new)

gu

['강남구',
 '성동구',
 '광진구',
 '동대문구',
 '관악구',
 '영등포구',
 '양천구',
 '서초구',
 '강동구',
 '금천구',
 '구로구',
 '강서구',
 '종로구',
 '노원구',
 '마포구',
 '동작구',
 '용산구',
 '성북구',
 '중구',
 '강북구',
 '송파구',
 '중랑구',
 '은평구',
 '서대문구',
 '도봉구']

In [25]:
pip install --upgrade xlrd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 4.4 MB/s
Installing collected packages: xlrd
  Attempting uninstall: xlrd
    Found existing installation: xlrd 1.1.0
    Uninstalling xlrd-1.1.0:
      Successfully uninstalled xlrd-1.1.0
Successfully installed xlrd-2.0.1

In [8]:
df1 = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/인구밀도/2015 행정동별 인구밀도.xls")

df1

       기간  자치구     동        인구      면적   인구밀도
0    2015   합계    합계  10297138  605.25  17013
1    2015  종로구    소계    163822   23.91   6851
2    2015  종로구   사직동     10033    1.23   8157
3    2015  종로구   삼청동      3174    1.49   2130
4    2015  종로구   부암동     11217    2.27   4941
..    ...  ...   ...       ...     ...    ...
445  2015  강동구  둔촌1동     19264    0.92  20939
446  2015  강동구  둔촌2동     28988    0.98  29580
447  2015  강동구  암사1동     37753    1.02  37013
448  2015  강동구  천호2동     37065    1.57  23608
449  2015  강동구    길동     51720    2.17  23834

[450 rows x 6 columns]

In [10]:
df1['동'].unique()

array(['합계', '소계', '사직동', '삼청동', '부암동', '평창동', '무악동', '교남동', '가회동',
       '종로1.2.3.4가동', '종로5·6가동', '이화동', '창신1동', '창신2동', '창신3동', '숭인1동',
       '숭인2동', '청운효자동', '혜화동', '소공동', '회현동', '명동', '필동', '장충동', '광희동',
       '을지로동', '신당5동', '황학동', '중림동', '신당동', '다산동', '약수동', '청구동', '동화동',
       '후암동', '용산2가동', '남영동', '원효로2동', '효창동', '용문동', '이촌1동', '이촌2동',
       '이태원1동', '이태원2동', '서빙고동', '보광동', '청파동', '원효로1동', '한강로동', '한남동',
       '왕십리2동', '마장동', '사근동', '행당1동', '행당2동', '응봉동', '금호1가동', '금호4가동',
       '성수1가1동', '성수1가2동', '성수2가1동', '성수2가3동', '송정동', '용답동', '왕십리도선동',
       '금호2.3가동', '옥수동', '화양동', '군자동', '중곡1동', '중곡2동', '중곡3동', '중곡4동',
       '능동', '구의1동', '구의2동', '구의3동', '광장동', '자양1동', '자양2동', '자양3동',
       '자양4동', '회기동', '휘경1동', '휘경2동', '청량리동', '용신동', '제기동', '전농1동',
       '전농2동', '답십리1동', '답십리2동', '장안1동', '장안2동', '이문1동', '이문2동', '면목2동',
       '면목4동', '면목5동', '면목7동', '상봉1동', '상봉2동', '중화1동', '중화2동', '묵1동',
       '묵2동', '망우3동', '신내1동', '신내2동', '면목본동', '면목3.8동', '망우본동', '돈암1동',
       '돈암2동', '안암동', '보문동', '정릉1동', '정릉2동', '정릉3동', '정릉4동', '길음1동',
       '길음2동', '월곡1동', '월곡2동', '장위1동', '장위2동', '장위3동', '성북동', '삼선동',
       '동선동', '종암동', '석관동', '번1동', '번2동', '번3동', '수유1동', '수유2동', '수유3동',
       '삼양동', '미아동', '송중동', '송천동', '삼각산동', '우이동', '인수동', '쌍문1동', '쌍문2동',
       '쌍문3동', '쌍문4동', '방학1동', '방학2동', '방학3동', '창1동', '창2동', '창3동', '창4동',
       '창5동', '도봉1동', '도봉2동', '월계1동', '월계2동', '월계3동', '공릉2동', '하계1동',
       '하계2동', '중계본동', '중계1동', '중계4동', '상계1동', '상계2동', '상계5동', '상계8동',
       '상계9동', '상계10동', '상계3.4동', '상계6.7동', '중계2.3동', '공릉1동', '녹번동',
       '불광1동', '갈현1동', '갈현2동', '구산동', '대조동', '응암1동', '응암2동', '신사1동',
       '신사2동', '증산동', '수색동', '진관동', '불광2동', '응암3동', '역촌동', '천연동', '홍제1동',
       '홍제3동', '홍제2동', '홍은1동', '홍은2동', '남가좌1동', '남가좌2동', '북가좌1동', '북가좌2동',
       '충현동', '북아현동', '신촌동', '연희동', '용강동', '대흥동', '염리동', '신수동', '서교동',
       '합정동', '망원1동', '망원2동', '연남동', '성산1동', '성산2동', '상암동', '도화동', '서강동',
       '공덕동', '아현동', '목1동', '목2동', '목3동', '목4동', '신월1동', '신월2동', '신월3동',
       '신월4동', '신월5동', '신월6동', '신월7동', '신정1동', '신정2동', '신정3동', '신정6동',
       '신정7동', '목5동', '신정4동', '염창동', '등촌1동', '등촌2동', '등촌3동', '화곡본동',
       '화곡2동', '화곡3동', '화곡4동', '화곡6동', '화곡8동', '가양1동', '가양2동', '가양3동',
       '발산1동', '공항동', '방화1동', '방화2동', '방화3동', '화곡1동', '우장산동', '신도림동',
       '구로1동', '구로3동', '구로4동', '구로5동', '고척1동', '고척2동', '개봉2동', '개봉3동',
       '오류1동', '오류2동', '수궁동', '가리봉동', '구로2동', '개봉1동', '가산동', '독산1동',
       '독산2동', '독산3동', '독산4동', '시흥1동', '시흥2동', '시흥3동', '시흥4동', '시흥5동',
       '여의동', '당산1동', '당산2동', '양평1동', '양평2동', '신길1동', '신길3동', '신길4동',
       '신길5동', '신길6동', '신길7동', '대림1동', '대림2동', '대림3동', '영등포본동', '영등포동',
       '도림동', '문래동', '노량진2동', '상도1동', '상도2동', '상도3동', '상도4동', '사당1동',
       '사당3동', '사당4동', '사당5동', '대방동', '신대방1동', '신대방2동', '흑석동', '노량진1동',
       '사당2동', '보라매동', '청림동', '행운동', '낙성대동', '중앙동', '인헌동', '남현동', '서원동',
       '신원동', '서림동', '신사동', '신림동', '난향동', '조원동', '대학동', '은천동', '성현동',
       '청룡동', '난곡동', '삼성동', '미성동', '서초1동', '서초2동', '서초3동', '서초4동', '잠원동',
       '반포본동', '반포1동', '반포2동', '반포3동', '반포4동', '방배본동', '방배1동', '방배2동',
       '방배3동', '방배4동', '양재1동', '양재2동', '내곡동', '논현1동', '논현2동', '삼성1동',
       '삼성2동', '대치1동', '대치4동', '역삼1동', '역삼2동', '도곡1동', '도곡2동', '개포1동',
       '개포4동', '일원본동', '일원1동', '일원2동', '수서동', '세곡동', '압구정동', '청담동',
       '대치2동', '개포2동', '풍납1동', '풍납2동', '거여1동', '거여2동', '마천1동', '마천2동',
       '방이1동', '방이2동', '오륜동', '오금동', '송파1동', '송파2동', '석촌동', '삼전동', '가락본동',
       '가락1동', '가락2동', '문정1동', '문정2동', '장지동', '위례동', '잠실본동', '잠실4동',
       '잠실6동', '잠실7동', '잠실2동', '잠실3동', '강일동', '상일동', '명일1동', '명일2동',
       '고덕1동', '고덕2동', '암사2동', '암사3동', '천호1동', '천호3동', '성내1동', '성내2동',
       '성내3동', '둔촌1동', '둔촌2동', '암사1동', '천호2동', '길동'], dtype=object)

In [18]:
dong = []
for i in range(len(table_2015)):
    new = table_2015['address'][i].split()[2]
    if new in dong: continue
    dong.append(new)

dong # 도로명 주소가 문제가 되는 중

['대치동',
 '성수동2가',
 '구의동',
 '용두동',
 '옥수동',
 '자곡동',
 '논현동',
 '봉천동',
 '영등포동3가',
 '목동',
 '서초동',
 '성내동',
 '가산동',
 '신정동',
 '구로동',
 '등촌동',
 '당산동3가',
 '필운동',
 '암사동',
 '도림동',
 '청량리동',
 '답십리동',
 '상계동',
 '시흥동',
 '종로5가',
 '서교동',
 '흑석동',
 '금호동1가',
 '천호동',
 '자양동',
 '역삼동',
 '반포동',
 '한남동',
 '신길동',
 '장위동',
 '문래동4가',
 '당산동5가',
 '내발산동',
 '광장동',
 '서계동',
 '성수동1가',
 '양평동3가',
 '양재동',
 '양평동2가',
 '보문동4가',
 '상암동',
 '정동',
 '신월동',
 '중계동',
 '장안동',
 '청담동',
 '화곡동',
 '성산동',
 '수유동',
 '오류동',
 '한강로3가',
 '신대방동',
 '가락동',
 '신내동',
 '신사동',
 '양평동5가',
 '가양동',
 '응암동',
 '신도림동',
 '독산동',
 '삼성동',
 '개봉동',
 '한강로1가',
 '연희동',
 '돈암동',
 '홍지동',
 '당산동1가',
 '고척동',
 '당산동2가',
 '가리봉동',
 '창동',
 '길음동',
 '여의도동',
 '충무로2가',
 '양평동4가',
 '월계동',
 '상봉동',
 '종암동',
 '평동',
 '행당동',
 '노고산동',
 '후암동',
 '한강로2가',
 '갈현동',
 '을지로6가',
 '을지로7가',
 '신천동',
 '묘동',
 '황학동',
 '남영동',
 '문정동',
 '문래동5가',
 '공덕동',
 '숭인동',
 '일원동',
 '예지동',
 '대조동',
 '대현동',
 '평창동',
 '문래동3가',
 '온수동',
 '길동',
 '염창동',
 '상수동',
 '이태원동',
 '무악동',
 '용답동',
 '장교동',
 '삼선동5가',
 '초동',
 '신당동',
 '쌍림동',
 '방화동',
 '북가좌동',
 '중곡동',
 '사직동',
 '이촌동',
 '남현동',
 '신림동',
 '방배동',
 '대림동',
 '제기동',
 '중화동',
 '원서동',
 '당산동6가',
 '돈의동',
 '문배동',
 '관수동',
 '주교동',
 '도화동',
 '명일동',
 '삼청동',
 '중림동',
 '남대문로5가',
 '인의동',
 '신수동',
 '홍제동',
 '도원동',
 '진관동',
 '하월곡동',
 '화양동',
 '방이동',
 '창신동',
 '영등포동',
 '동자동',
 '남창동',
 '마천동',
 '수서동',
 '청파동1가',
 '합동',
 '합정동',
 '장지동',
 '전농동',
 '정릉동',
 '필동2가',
 '도봉동',
 '미아동',
 '대방동',
 '거여동',
 '신계동',
 '불광동',
 '동소문동7가',
 '영등포동6가',
 '대흥동',
 '개포동',
 '공항동',
 '인현동2가',
 '부암동',
 '우면동',
 '방학동',
 '명륜동2가',
 '경운동',
 '쌍문동',
 '용산동5가',
 '도곡동',
 '동선동1가',
 '창전동',
 '신설동',
 '문래동6가',
 '상도동',
 '강일동',
 '서빙고동',
 '산림동',
 '충무로4가',
 '역촌동',
 '마포동',
 '인사동',
 '영등포동2가',
 '율현동',
 '영등포동5가',
 '면목동',
 '영등포동8가',
 '수색동',
 '광희동1가',
 '번동',
 '입정동',
 '수송동',
 '망원동',
 '잠실동',
 '동소문동5가',
 '다동',
 '영등포동7가',
 '당산동4가',
 '마장동']

In [32]:
table_2015['address'][2].split()[2]

['서울', '성동구', '성수동2가', '351', '2층', '203호']

In [33]:
doro = []
for i in range(len(table_2015)):
    new = table_2015['address'][i].split()[2][-1]
    if new == '동': continue
    doro.append(table_2015['address'][i])

doro

['서울 성동구 성수동2가 351 2층 203호',
 '서울 영등포구 영등포동3가 9-13 지하 1층 비1038호',
 '서울 영등포구 당산동3가 558-3 더파크365 7층 719호',
 '서울 성동구 성수동2가 333-97',
 '서울 성동구 성수동2가 300-4 영동테크노타워 지하 2층 2204호',
 '서울 영등포구 당산동3가 558-3 5층 501호',
 '서울 종로구 종로5가 314-7 청오가방도매상가 4층 449호',
 '서울 성동구 금호동1가 108 금호타워빌 2층 201호',
 '서울 영등포구 문래동4가 29-8',
 '서울 영등포구 당산동5가 11-34 삼성타운 1층 117호',
 '서울 성동구 성수동2가 284-55 서울숲에스케이브이1타워 에이동 5층 507호',
 '서울 성동구 성수동1가 16-4 에스케이테크노빌딩 6층 607호',
 '서울 영등포구 양평동3가 34 양평역대우미래사랑 비동 10층 1101호',
 '서울 영등포구 양평동2가 1-2 3층 303호',
 '서울 영등포구 양평동2가 1-2 7층 707호',
 '서울 성북구 보문동4가 116 보문하우스토리 1층 118호',
 '서울 영등포구 당산동3가 558-3 더파크365 8층 801호',
 '서울 영등포구 당산동3가 558-3 6층 601호',
 '서울 영등포구 당산동5가 11-34 삼성타운 2층 219호',
 '서울 용산구 한강로3가 63-387 용산시티파크 2층 206호',
 '서울 영등포구 양평동5가 92 대우미래사랑2차 102동 14층 1402호',
 '서울 영등포구 당산동3가 558-3 더파크365 3층 308호',
 '서울 용산구 한강로1가 50-1 용산파크자이 10층 디-1032호',
 '서울 영등포구 당산동1가 9-1 3층 46호',
 '서울 영등포구 당산동2가 30-2 2층 바열15호',
 '서울 영등포구 당산동2가 30-2 2층 라열32호',
 '서울 영등포구 당산동2가 30-2 1층 바열26호',
 '서울 중구 충무로2가 63   -5     충무로패션몰리지상가 1층 151-1         호',
 '서울 중구 충무로2가 63   -5     충무로패션몰리지상가 1층 106-1         호',
 '서울 영등포구 양평동4가 22-1 4층 402호',
 '서울 용산구 한강로2가 15-14 22동 7층 7042호',
 '서울 중구 을지로6가 18-21 2층 에프2136호',
 '서울 중구 을지로6가 18-21 2층 에프2137호',
 '서울 중구 을지로7가 105 4층 4044호',
 '서울 중구 을지로6가 18-21 지하 1층 비1185호',
 '서울 중구 을지로6가 18-21 지하 1층 비1186호',
 '서울 영등포구 문래동5가 2 지하 2층 201호',
 '서울 영등포구 문래동3가 55-16 1층 에이치02호',
 '서울 중구 을지로7가 105 라모도쇼핑몰 6층 6106호',
 '서울 중구 을지로6가 18-21 굿모닝시티쇼핑몰 5층 에프5071호',
 '서울 중구 을지로6가 18-21 지하 2층 비2056호',
 '서울 중구 을지로6가 18-21 4층 에프4421호',
 '서울 용산구 한강로2가 15-37 비동 3층 349호',
 '서울 영등포구 영등포동3가 7 7층 7028호',
 '서울 중구 을지로6가 18-21 4층 에프4269호',
 '서울 성북구 삼선동5가 289',
 '서울 중구 을지로6가 18-21 4층 에프4008호',
 '서울 중구 을지로6가 18-21 4층 에프4009호',
 '서울 영등포구 문래동3가 55-16 2층 에이01호',
 '서울 중구 을지로7가 105 1층 1084호',
 '서울 영등포구 영등포동3가 7 4층 4104호',
 '서울 용산구 한강로2가 15-37 비동 4층 447호',
 '서울 중구 을지로6가 18-21 3층 에프4056호',
 '서울 중구 을지로6가 18-21 4층 에프4329호',
 '서울 용산구 한강로2가 107-10 4층 401호',
 '서울 중구 을지로6가 18-35 지하 2층 1호',
 '서울 영등포구 문래동3가 55-20 1층 1-102호',
 '서울 중구 을지로7가 105 3층 3045호',
 '서울 영등포구 문래동3가 55-16 1층 비06호',
 '서울 영등포구 영등포동3가 7 1층 1058호',
 '서울 영등포구 영등포동3가 7 1층 1059호',
 '서울 영등포구 영등포동3가 7 1층 1060호',
 '서울 중구 을지로6가 18-21 7층 에프7280호',
 '서울 용산구 한강로2가 15-37 비동 3층 301호',
 '서울 중구 을지로6가 18-21 3층 에프3337호',
 '서울 영등포구 영등포동3가 7 3층 3032호',
 '서울 성동구 성수동2가 277-43 3층 302호',
 '서울 종로구 종로5가 398-1',
 '서울 중구 을지로6가 18-185 5층 214호',
 '서울 영등포구 당산동6가 237-41',
 '서울 영등포구 당산동6가 237-42',
 '서울 중구 을지로7가 105 라모도쇼핑몰 1층 1135호',
 '서울 영등포구 문래동5가 9 벽산디지털밸리 1층 105호',
 '서울 중구 남대문로5가 827 1층 102호',
 '서울 영등포구 영등포동3가 7 3층 3118호',
 '서울 영등포구 영등포동3가 8 1층 105호',
 '서울 영등포구 영등포동3가 8 1층 120호',
 '서울 영등포구 영등포동3가 8 2층 203호',
 '서울 중구 을지로6가 18-35 4층 26호',
 '서울 중구 을지로7가 105 라모도쇼핑몰 2층 2058호',
 '서울 성동구 성수동2가 289-319 성수동아이에스비즈타워 6층 604호',
 '서울 영등포구 당산동6가 306-1 지하 1층 1호',
 '서울 영등포구 당산동3가 558-3 더파크365 2층 204호',
 '서울 용산구 청파동1가 89-43 1층 101호',
 '서울 종로구 종로5가 314-7 4층 448호',
 '서울 성동구 성수동2가 281-16 3층 303호',
 '서울 성동구 성수동2가 280-21 성수동우림이비즈센터 10층 1006호',
 '서울 중구 필동2가 124-1',
 '서울 영등포구 문래동3가 55-16 28층 1-2804호',
 '서울 용산구 청파동1가 6-1 2층 203호',
 '서울 영등포구 양평동4가 23-7 4층 401호',
 '서울 성동구 성수동2가 300-4 영동테크노타워 4층 408호',
 '서울 중구 충무로2가 63   -5     충무로패션몰리지상가 1층 141-1         호',
 '서울 성동구 성수동1가 13-12 에이동 7층 713호',
 '서울 영등포구 양평동4가 23-7 지하 1층 비101호',
 '서울 영등포구 양평동4가 23-7 지하 2층 비201호',
 '서울 용산구 한강로2가 25-1 2층 201호',
 '서울 용산구 한강로1가 221-7 2층 201호',
 '서울 성북구 동소문동7가 120 브라운스톤동선 상가동 2층 201호',
 '서울 영등포구 영등포동6가 8-3',
 '서울 영등포구 양평동4가 23-7 4층 404호',
 '서울 영등포구 양평동4가 23-7 4층 405호',
 '서울 영등포구 양평동4가 23-7 4층 406호',
 '서울 영등포구 당산동2가 30-2 영등포유통상가 지하 2층 지하2층호',
 '서울 중구 을지로6가 18-21 지하 2층 비2034호',
 '서울 중구 을지로6가 18-21 지하 2층 비2035호',
 '서울 중구 을지로7가 105 라모도쇼핑몰 3층 3099호',
 '서울 중구 을지로7가 105 라모도쇼핑몰 3층 3100호',
 '서울 영등포구 문래동3가 55-16 1층 에프11호',
 '서울 중구 을지로6가 18-21 5층 에프5143호',
 '서울 용산구 청파동1가 89-43 3층 302호',
 '서울 영등포구 당산동3가 558-3 4층 413호',
 '서울 중구 인현동2가 128-25',
 '서울 영등포구 문래동5가 2 8층 808호',
 '서울 영등포구 문래동5가 2 8층 809호',
 '서울 영등포구 당산동2가 30-2 지하 1층 마열59호',
 '서울 중구 인현동2가 37',
 '서울 종로구 명륜동2가 21-11',
 '서울 영등포구 당산동2가 30-2 3층 나열39호',
 '서울 영등포구 양평동4가 23-7 1층 101호',
 '서울 용산구 용산동5가 24-1 1층 상가26호',
 '서울 성북구 동선동1가 1-2 8층 8011호',
 '서울 영등포구 양평동4가 23-7 3층 301호',
 '서울 중구 을지로6가 18-185 6층 50호',
 '서울 영등포구 양평동4가 23-7 6층 606호',
 '서울 중구 을지로6가 18-21 1층 에프1418호',
 '서울 용산구 청파동1가 89-43 2층 202호',
 '서울 영등포구 양평동4가 23-7 1층 102호',
 '서울 영등포구 당산동5가 33-1 지하 1층 비109호',
 '서울 영등포구 당산동5가 33-1 지하 1층 비110호',
 '서울 영등포구 당산동5가 33-1 지하 1층 비111호',
 '서울 용산구 한강로2가 2-8 26층 104-2615호',
 '서울 영등포구 문래동6가 5-2 8층 803호',
 '서울 영등포구 양평동3가 46 3층 301호',
 '서울 성북구 동선동1가 1-2 지하 1층 비1098호',
 '서울 성북구 동선동1가 1-2 2층 2001호',
 '서울 중구 을지로6가 18-21 5층 에프5044호',
 '서울 중구 충무로4가 151-6',
 '서울 중구 충무로2가 63   -5     충무로패션몰리지상가 1층 103           호',
 '서울 영등포구 양평동4가 23-7 2층 201호',
 '서울 중구 을지로7가 105 4층 4109호',
 '서울 영등포구 양평동4가 23-7 3층 303호',
 '서울 중구 충무로2가 63   -5     충무로패션몰리지상가 3층 361           호',
 '서울 영등포구 당산동3가 558-3 11층 1105호',
 '서울 중구 충무로2가 63-5 1층 120호',
 '서울 중구 충무로2가 63-5 1층 163호',
 '서울 중구 충무로2가 63-5 2층 203호',
 '서울 중구 충무로2가 63-5 2층 238호',
 '서울 중구 충무로2가 63-5 2층 247호',
 '서울 중구 충무로2가 63-5 3층 338호',
 '서울 중구 충무로2가 63-5 3층 340호',
 '서울 중구 충무로2가 63-5 3층 362호',
 '서울 영등포구 양평동5가 106-1 10층 에이1001호',
 '서울 영등포구 양평동4가 23-7 5층 505호',
 '서울 영등포구 양평동4가 23-7 5층 506호',
 '서울 영등포구 영등포동2가 94-119 7층 709호',
 '서울 영등포구 영등포동2가 94-119 8층 812호',
 '서울 영등포구 영등포동5가 81-1 4층 402호',
 '서울 영등포구 양평동4가 23-7 2층 202호',
 '서울 영등포구 양평동4가 23-7 2층 203호',
 '서울 영등포구 양평동4가 23-7 2층 204호',
 '서울 영등포구 양평동4가 23-7 2층 205호',
 '서울 영등포구 영등포동8가 92 19층 1906호',
 '서울 영등포구 문래동3가 54-37 3층 1호',
 '서울 중구 광희동1가 89-1 1동 10층 1004호',
 '서울 영등포구 양평동2가 1-1 2층 104-201호',
 '서울 영등포구 영등포동2가 28-153 2층 204호',
 '서울 영등포구 영등포동2가 28-153 6층 603호',
 '서울 성북구 동소문동5가 120 1층 104호',
 '서울 영등포구 영등포동7가 94-190 7층 703호',
 '서울 영등포구 당산동4가 74-2 4층 405호',
 '서울 영등포구 문래동3가 55-4 101동 30층 3001호',
 '서울 영등포구 양평동4가 23-7 2층 207호']

In [36]:
textfile = open("/content/drive/MyDrive/기쁨코인/dataset/table2015_도로명주소_file.txt", "w")
for element in doro:
    textfile.write(element + "\n")
textfile.close()

In [ ]:
# https://www.juso.go.kr/CommonPageLink.do?link=/support/AddressTransformThousand
# 도로명주소를 지번주소로 바꿔주는 곳인데 여기서 하려다가 에러를 띄웠습니다.
# 편의상 구 단위로만 인구밀도를 붙이는 것도 의미있다고 사료되어 그 작업만 하겠습니다.

In [62]:
pop_density = df1[df1['동']=='소계']

pop_density = pop_density.drop(['기간', '동'], axis=1).reset_index(drop=True)

pop_density

     자치구      인구     면적   인구밀도
0    종로구  163822  23.91   6851
1     중구  134329   9.96  13486
2    용산구  247909  21.87  11337
3    성동구  305065  16.86  18093
4    광진구  375180  17.06  21987
5   동대문구  373824  14.21  26301
6    중랑구  418620  18.50  22633
7    성북구  469560  24.58  19104
8    강북구  334426  23.60  14172
9    도봉구  353241  20.71  17056
10   노원구  578221  35.44  16317
11   은평구  502578  29.70  16920
12  서대문구  323105  17.61  18351
13   마포구  398351  23.84  16706
14   양천구  489010  17.40  28098
15   강서구  595691  41.44  14376
16   구로구  454604  20.12  22596
17   금천구  256167  13.02  19675
18  영등포구  417811  24.53  17033
19   동작구  412774  16.35  25240
20   관악구  529031  29.57  17891
21   서초구  451258  47.00   9601
22   강남구  581760  39.50  14728
23   송파구  667480  33.88  19704
24   강동구  463321  24.59  18842

In [63]:
pop_num = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/인구/2015-2017 서울시 자치구별 주민등록인구.xls")

# 첫번째 행인 합계 삭제, 기타 힐요없는 행 삭제
pop_num = pop_num.loc[pop_num['기간']==2015].reset_index(drop=True).drop(0, axis=0).drop(['기간', '계'], axis=1)

pop_num

,자치구,세대,남자 합계,여자 합계,한국인 합계,한국인 남자,한국인 여자,등록외국인 합계,등록외국인 남자,등록외국인 여자,세대당인구,65세이상고령자
1,종로구,72645,80531,83291,154986,76548,78438,8836,3983,4853,2.13,24892
2,중구,59321,66755,67574,125733,62687,63046,8596,4068,4528,2.12,20302
3,용산구,107512,121027,126882,233342,113177,120165,14567,7850,6717,2.17,35715
4,성동구,126714,151459,153606,297003,147570,149433,8062,3889,4173,2.34,38164
5,광진구,158353,183436,191744,360369,176884,183485,14811,6552,8259,2.28,40368
6,동대문구,159941,185827,187997,360153,180485,179668,13671,5342,8329,2.25,52490
7,중랑구,176390,208393,210227,413909,206505,207404,4711,1888,2823,2.35,54095
8,성북구,190973,229183,240377,459275,224980,234295,10285,4203,6082,2.40,63281
9,강북구,141088,164337,170089,330873,162967,167906,3553,1370,2183,2.35,52598
10,도봉구,136903,173804,179437,351242,173029,178213,1999,775,1224,2.57,48590
11,노원구,219768,281538,296683,574583,279987,294596,3638,1551,2087,2.61,68909
12,은평구,203410,244964,257614,497920,242975,254945,4658,1989,2669,2.45,69753
13,서대문구,135770,156130,166975,312141,152008,160133,10964,4122,6842,2.30,46758
14,마포구,171480,190957,207394,387643,186495,201148,10708,4462,6246,2.26,48598
15,양천구,179512,242074,246936,484532,239995,244537,4478,2079,2399,2.70,50398
16,강서구,238952,291216,304475,589074,287947,301127,6617,3269,3348,2.47,67950
17,구로구,172321,228201,226403,422092,210440,211652,32512,17761,14751,2.45,53719
18,금천구,103847,131346,124821,236284,120604,115680,19883,10742,9141,2.28,31070
19,영등포구,167863,210388,207423,378504,189394,189110,39307,20994,18313,2.25,51481
20,동작구,170495,202165,210609,400641,196463,204178,12133,5702,6431,2.35,53610
21,관악구,249191,266773,262258,509663,257491,252172,19368,9282,10086,2.05,64985
22,서초구,173007,217036,234222,446764,214737,232027,4494,2299,2195,2.58,49280
23,강남구,237373,279209,302551,576495,276425,300070,5265,2784,2481,2.43,60330
24,송파구,256611,325950,341530,660302,322441,337861,7178,3509,3669,2.57,68292
25,강동구,180508,230851,232470,458658,228709,229949,4663,2142,2521,2.54,51935

In [64]:
pop = pop_density.merge(pop_num, how='inner')

pop

,자치구,인구,면적,인구밀도,세대,남자 합계,여자 합계,한국인 합계,한국인 남자,한국인 여자,등록외국인 합계,등록외국인 남자,등록외국인 여자,세대당인구,65세이상고령자
0,종로구,163822,23.91,6851,72645,80531,83291,154986,76548,78438,8836,3983,4853,2.13,24892
1,중구,134329,9.96,13486,59321,66755,67574,125733,62687,63046,8596,4068,4528,2.12,20302
2,용산구,247909,21.87,11337,107512,121027,126882,233342,113177,120165,14567,7850,6717,2.17,35715
3,성동구,305065,16.86,18093,126714,151459,153606,297003,147570,149433,8062,3889,4173,2.34,38164
4,광진구,375180,17.06,21987,158353,183436,191744,360369,176884,183485,14811,6552,8259,2.28,40368
5,동대문구,373824,14.21,26301,159941,185827,187997,360153,180485,179668,13671,5342,8329,2.25,52490
6,중랑구,418620,18.50,22633,176390,208393,210227,413909,206505,207404,4711,1888,2823,2.35,54095
7,성북구,469560,24.58,19104,190973,229183,240377,459275,224980,234295,10285,4203,6082,2.40,63281
8,강북구,334426,23.60,14172,141088,164337,170089,330873,162967,167906,3553,1370,2183,2.35,52598
9,도봉구,353241,20.71,17056,136903,173804,179437,351242,173029,178213,1999,775,1224,2.57,48590
10,노원구,578221,35.44,16317,219768,281538,296683,574583,279987,294596,3638,1551,2087,2.61,68909
11,은평구,502578,29.70,16920,203410,244964,257614,497920,242975,254945,4658,1989,2669,2.45,69753
12,서대문구,323105,17.61,18351,135770,156130,166975,312141,152008,160133,10964,4122,6842,2.30,46758
13,마포구,398351,23.84,16706,171480,190957,207394,387643,186495,201148,10708,4462,6246,2.26,48598
14,양천구,489010,17.40,28098,179512,242074,246936,484532,239995,244537,4478,2079,2399,2.70,50398
15,강서구,595691,41.44,14376,238952,291216,304475,589074,287947,301127,6617,3269,3348,2.47,67950
16,구로구,454604,20.12,22596,172321,228201,226403,422092,210440,211652,32512,17761,14751,2.45,53719
17,금천구,256167,13.02,19675,103847,131346,124821,236284,120604,115680,19883,10742,9141,2.28,31070
18,영등포구,417811,24.53,17033,167863,210388,207423,378504,189394,189110,39307,20994,18313,2.25,51481
19,동작구,412774,16.35,25240,170495,202165,210609,400641,196463,204178,12133,5702,6431,2.35,53610
20,관악구,529031,29.57,17891,249191,266773,262258,509663,257491,252172,19368,9282,10086,2.05,64985
21,서초구,451258,47.00,9601,173007,217036,234222,446764,214737,232027,4494,2299,2195,2.58,49280
22,강남구,581760,39.50,14728,237373,279209,302551,576495,276425,300070,5265,2784,2481,2.43,60330
23,송파구,667480,33.88,19704,256611,325950,341530,660302,322441,337861,7178,3509,3669,2.57,68292
24,강동구,463321,24.59,18842,180508,230851,232470,458658,228709,229949,4663,2142,2521,2.54,51935

In [65]:
df3 = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/지역내 총생산/2015 지역내총생산.xls").drop("기간", axis=1)

df3

     자치구  지역내총생산(당해년가격)   구성비  지역내총생산(2015년 기준년 연쇄가격)  전년대비 증감률
0    종로구       29331069   7.9                29331069       1.9
1     중구       49949249  13.5                49949249       6.2
2    용산구       10023473   2.7                10023473       0.1
3    성동구       10231864   2.8                10231864       3.6
4    광진구        5696485   1.5                 5696485      -0.6
5   동대문구        6589147   1.8                 6589147      -2.4
6    중랑구        3856334   1.0                 3856334      -5.1
7    성북구        5407042   1.5                 5407042       0.4
8    강북구        2759140   0.7                 2759140      -3.7
9    도봉구        2906723   0.8                 2906723      -2.0
10   노원구        5606176   1.5                 5606176       0.4
11   은평구        3866400   1.0                 3866400       1.7
12  서대문구        7507777   2.0                 7507777       0.8
13   마포구       17955655   4.9                17955655       2.2
14   양천구        6276755   1.7                 6276755       0.1
15   강서구       10149098   2.7                10149098       6.4
16   구로구       12017187   3.2                12017187       0.9
17   금천구       14953994   4.0                14953994       1.5
18  영등포구       30173741   8.2                30173741       3.9
19   동작구        5521181   1.5                 5521181      -4.4
20   관악구        5597548   1.5                 5597548      -1.4
21   서초구       30390265   8.2                30390265       2.8
22   강남구       62295492  16.8                62295492       5.3
23   송파구       23586997   6.4                23586997       4.3
24   강동구        7519077   2.0                 7519077      -0.5

In [80]:
df4 = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/자치구별 총 부가가치/2015 자치구별 총부가가치.xls")

df4 = df4.drop(['기간', '광업 ', '광업 증감률'], axis=1) # 결측치가 존재했었는데 NaN이 아니라 -, ... 이런식이었음

df4

,자치구,지역내총부가가치(2015년 기준년연쇄가격),지역내총부가가치 증감률,농업 임업 및 어업,농업 임업 및 어업 증감률,제조업,제조업 증감률,전기가스증기 및 공기조절 공급업,전기가스증기 및 공기조절 공급업 증감률,건설업,...,공공행정국방및사회보장행정,공공행정국방및사회보장행정 증감률,교육서비스업,교육서비스업 증감률,보건업 및 사회복지 서비스업,보건업 및 사회복지 서비스업 증감률,문화 및 기타서비스업,문화 및 기타서비스업 증감률,순생산물세,순생산물세 증감률
0,종로구,26739280,1.4,9035,-29.9,214522,-75.3,57542,-1.4,399972,...,4553886,5.8,796466,2.4,899873,11.5,621479,-4.1,2591790,7.4
1,중구,45167477,5.7,19,40.6,664678,-42.5,74527,-4.0,525314,...,2191163,2.5,674909,4.0,555751,6.2,598820,-3.9,4781771,11.8
2,용산구,9269553,0.1,11335,-40.5,134846,-31.7,49327,-1.1,419151,...,1713624,-3.5,351998,10.6,239529,10.2,380706,-1.1,753920,1.0
3,성동구,9411610,3.9,403,-4.7,2153150,6.8,60090,-1.9,544764,...,173559,-4.0,680190,8.1,277008,6.2,371563,1.8,820254,0.6
4,광진구,5298822,-0.6,108,6.1,357576,-2.2,59613,-0.5,172254,...,160594,-7.7,609295,1.8,406856,4.5,307241,-8.0,397663,-0.3
5,동대문구,6088070,-2.0,136,-12.4,494438,-24.6,54365,-0.1,287477,...,162986,-12.1,868680,7.2,555040,12.2,319212,-7.9,501078,-7.2
6,중랑구,3564990,-5.1,1735,-6.0,193249,-39.6,50541,1.9,175337,...,134716,-16.1,363225,-3.2,316346,8.4,255180,-16.4,291344,-5.2
7,성북구,5080333,0.4,346,7.9,138265,-27.9,63886,-0.4,251239,...,169790,-14.6,1216929,4.9,453301,5.5,235259,-6.6,326710,1.9
8,강북구,2554343,-3.8,382,14.8,83470,-23.4,42228,-0.7,123863,...,130064,-12.9,243929,-6.5,272142,5.8,191499,-11.3,204797,-2.8
9,도봉구,2689643,-2.2,956,0.1,101885,-31.5,44080,-2.1,108949,...,197330,-3.7,297742,-1.1,252351,7.5,181540,-6.1,217080,0.1
10,노원구,5245749,-0.1,1031,2.9,150573,-7.9,71259,-0.6,186199,...,165215,-17.9,1097256,4.5,654138,6.0,221634,-6.0,360427,7.6
11,은평구,3595942,1.4,2817,-2.3,62718,-29.1,59774,-0.2,303764,...,149060,-16.7,416991,-3.4,420385,4.9,189484,-6.7,270458,5.6
12,서대문구,6972630,0.5,84469,-31.2,63627,-33.7,49142,-1.0,320157,...,652210,8.4,1165291,-2.9,791702,21.3,166324,-4.5,535147,4.3
13,마포구,16748565,2.1,845,-5.4,215727,-16.2,70881,0.0,441071,...,210457,-10.1,780767,-0.4,392709,8.8,536843,-1.5,1207090,3.5
14,양천구,5857062,-0.2,238,14.8,273606,28.0,75652,-1.2,255942,...,255882,-32.7,629338,-0.2,479446,7.3,269501,-1.8,419692,4.4
15,강서구,9371637,6.1,12518,-5.2,383353,11.3,72492,-1.8,972792,...,159805,-17.0,636193,3.6,526275,9.6,412217,-2.9,777461,9.4
16,구로구,11124833,0.8,2127,-5.0,1530885,5.5,66436,-1.6,207557,...,204162,-0.4,488507,-1.8,496933,4.2,292209,-3.4,892354,2.4
17,금천구,13959816,1.7,164,3.9,3543806,9.5,49079,-3.9,185123,...,116705,-10.1,230025,-2.6,194247,4.1,227329,-0.5,994178,-0.5
18,영등포구,27065451,2.9,3452,23.0,729420,-22.0,81121,-2.7,465916,...,667494,-11.8,462250,-5.9,589557,6.6,903455,-4.6,3108290,13.8
19,동작구,5140537,-4.4,165,2.3,30254,-53.2,55034,-0.8,244491,...,239417,-4.6,745592,2.7,473427,5.1,190843,-8.8,380644,-3.4
20,관악구,5236213,-1.4,600,9.1,114808,-33.9,71365,-0.2,320764,...,164514,-17.5,881967,0.1,325896,6.7,281527,-5.7,361335,-1.9
21,서초구,28113571,2.8,186110,-23.2,868240,21.8,107119,-2.8,719278,...,1583789,-2.5,1080950,5.1,1170816,8.5,824725,2.0,2276694,2.8
22,강남구,56866154,5.4,25151,-17.7,2875272,45.0,153097,-4.7,998532,...,275093,-16.1,1588177,0.0,2419185,6.4,1586264,-3.7,5429338,4.8
23,송파구,21721787,4.5,42326,-18.8,854599,-2.8,98972,-1.9,1447083,...,287552,-13.5,774431,0.4,1266772,7.8,1566148,-5.8,1865209,2.1
24,강동구,6911857,-0.6,4756,-10.2,434639,8.9,66811,6.3,401854,...,142598,-15.9,424703,-4.1,736699,3.5,307841,-9.9,607220,0.3

In [67]:
df4.columns

Index(['기간', '자치구', '지역내총부가가치(2015년 기준년연쇄가격)', '지역내총부가가치 증감률', '농업 임업 및 어업',
       '농업 임업 및 어업 증감률', '광업 ', '광업 증감률', '제조업 ', '제조업 증감률',
       '전기가스증기 및  공기조절 공급업', '전기가스증기 및  공기조절 공급업 증감률', '건설업', '건설업 증감률',
       '도매 및 소매업', '도매 및 소매업 증감률', '운수 및 창고업', '운수 및 창고업 증감률', '숙박 및 음식점업',
       '숙박 및 음식점업 증감률', '정보통신업', '정보통신업 증감률', '금융 및 보험업', '금융 및 보험업 증감률',
       '부동산업', '부동산업 증감률', '사업서비스업', '사업서비스업 증감률', '공공행정국방및사회보장행정',
       '공공행정국방및사회보장행정 증감률', '교육서비스업', '교육서비스업 증감률', '보건업 및 사회복지 서비스업',
       '보건업 및 사회복지 서비스업 증감률', '문화 및 기타서비스업 ', '문화 및 기타서비스업 증감률', '순생산물세',
       '순생산물세 증감률'],
      dtype='object')

In [76]:
# 이제 table 2015에 '자치구' 열을 만들어 그 열을 기준으로 merge하겠습니다.

AttributeError: ignored

In [82]:
for i in range(len(table_2015)):
    table_2015.loc[i, '자치구'] = table_2015['address'][i].split()[1]

In [84]:
table_2015

,building t,case num,address,Latitude,Longitude,size,appraiser,lowest,success,bid_date,...,병원_1km,대규모점포_0.4km,대규모점포_0.6km,대규모점포_0.8km,대규모점포_1km,관광극장유흥업_0.4km,관광극장유흥업_0.6km,관광극장유흥업_0.8km,관광극장유흥업_1km,자치구
0,오피스텔,2015 타경 12810,서울 강남구 대치동 889-47 비동 3층 317호,37.503835,127.050223,건물 38.71㎡(11.71평) / 대지권 7.75㎡(2.34평),202000000,161600000,191100000.0,2015/12/29,...,9,1,1,7,10,0,0,0,0,강남구
1,근린상가,2015 타경 179,서울 성동구 성수동2가 351 2층 203호,37.537619,127.051455,건물 61.25㎡(18.53평) / 대지권 48.18㎡(14.57평),425000000,217600000,235820000.0,2015/12/28,...,3,2,2,3,4,0,0,0,0,성동구
2,근린상가,2015 타경 4065,서울 광진구 구의동 546-4 테크노-마트21 5층 비066호,37.534937,127.095709,건물 11.07㎡(3.35평) / 대지권 2.93㎡(0.89평),52000000,41600000,NaN,2015/12/28,...,0,3,6,8,8,0,0,0,0,광진구
3,근린상가,2015 타경 5668,서울 동대문구 용두동 788 한방천하-용두동포스빌 2층 273호,37.577807,127.036898,건물 6.6㎡(2평) / 대지권 1.79㎡(0.54평),32000000,20480000,21289000.0,2015/12/28,...,8,7,9,12,15,0,0,0,0,동대문구
4,근린상가,2015 타경 5976,서울 성동구 옥수동 100 옥수하이츠 상가동 1층 112호,37.540118,127.016386,건물 27㎡(8.17평) / 대지권 24.72㎡(7.48평),130000000,130000000,151167100.0,2015/12/28,...,0,1,2,2,3,0,0,0,0,성동구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107,오피스텔,2014 타경 14320,서울 노원구 월계동 366-3 2층 201호,37.624881,127.060288,건물 33.75㎡(10.21평) / 대지권 13.58㎡(4.11평),125000000,100000000,103700000.0,2015/01/12,...,0,3,3,3,5,0,0,0,0,노원구
1108,오피스텔,2014 타경 4184,서울 영등포구 양평동4가 23-7 2층 207호,37.535671,126.894746,건물 32.21㎡(9.74평) / 대지권 11.51㎡(3.48평),205000000,164000000,185500000.0,2015/01/07,...,7,1,1,1,4,0,0,0,0,영등포구
1109,근린시설,2014 타경 3522,서울 성동구 마장동 767-27,37.568139,127.045086,건물 145.77㎡(44.1평) / 토지 99.8㎡(30.19평) / 제시외 71.2 ㎡,406059600,259878000,339555000.0,2015/01/05,...,5,0,1,3,5,0,0,0,0,성동구
1110,오피스텔,2014 타경 5955,서울 송파구 잠실동 175-1 10층 1005호,37.510752,127.078933,건물 33.92㎡(10.26평) / 대지권 8.26㎡(2.5평),160000000,128000000,141000000.0,2015/01/05,...,1,1,2,2,3,2,2,2,2,송파구
1111,근린상가,2014 타경 7623,서울 송파구 가락동 75 2층 201 호,37.496290,127.120726,건물 245.44㎡(74.25평),230000000,230000000,NaN,2015/07/06,...,8,0,3,4,6,0,0,0,0,송파구

In [87]:
# 인구 데이터와 inner join

table_2015_1 = table_2015.merge(pop, on=['자치구'], how='inner')

table_2015_1

,building t,case num,address,Latitude,Longitude,size,appraiser,lowest,success,bid_date,...,남자 합계,여자 합계,한국인 합계,한국인 남자,한국인 여자,등록외국인 합계,등록외국인 남자,등록외국인 여자,세대당인구,65세이상고령자
0,오피스텔,2015 타경 12810,서울 강남구 대치동 889-47 비동 3층 317호,37.503835,127.050223,건물 38.71㎡(11.71평) / 대지권 7.75㎡(2.34평),202000000,161600000,1.911000e+08,2015/12/29,...,279209,302551,576495,276425,300070,5265,2784,2481,2.43,60330
1,종교시설,2015 타경 2677,서울 강남구 자곡동 288,37.479831,127.102842,건물 797.09㎡(241.12평) / 토지 655㎡(198.14평) / 제시외 1...,3872438950,3097951000,3.133300e+09,2015/12/24,...,279209,302551,576495,276425,300070,5265,2784,2481,2.43,60330
2,근린상가,2015 타경 4680,서울 강남구 논현동 108 논현웰스톤 1층 162호,37.518417,127.038003,건물 129.21㎡(39.09평) / 대지권 40.77㎡(12.33평),784000000,627200000,7.017000e+08,2015/12/24,...,279209,302551,576495,276425,300070,5265,2784,2481,2.43,60330
3,근린상가,2015 타경 1056,서울 강남구 역삼동 815 점프밀라노 9층 901호,37.501275,127.026641,건물 86.45㎡(26.15평) / 대지권 17.95㎡(5.43평),430000000,430000000,9.950000e+08,2015/11/26,...,279209,302551,576495,276425,300070,5265,2784,2481,2.43,60330
4,근린시설,2015 타경 2585,서울 강남구 청담동 7,37.523254,127.047221,건물 1369.19㎡(414.18평) / 토지 431.9㎡(130.65평) / 제시...,8358750000,8358750000,9.311000e+09,2015/10/14,...,279209,302551,576495,276425,300070,5265,2784,2481,2.43,60330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107,근린상가,2014 타경 17879,서울 도봉구 창동 4 6층 1호,37.652865,127.049188,건물 307.59㎡(93.05평) / 대지권 91.98㎡(27.82평),703000000,562400000,6.010000e+08,2015/04/20,...,173804,179437,351242,173029,178213,1999,775,1224,2.57,48590
1108,근린상가,2014 타경 18551,서울 도봉구 도봉동 81-1 상가동 지하 1층 9호,37.682475,127.049372,건물 10.73㎡(3.25평) / 대지권 7.65㎡(2.31평),13000000,6656000,NaN,2015/04/13,...,173804,179437,351242,173029,178213,1999,775,1224,2.57,48590
1109,근린상가,2014 타경 18483,서울 도봉구 방학동 719-3 1층 108호,37.669193,127.045262,건물 23.89㎡(7.23평) / 대지권 7.1㎡(2.15평),145000000,116000000,1.171000e+08,2015/03/23,...,173804,179437,351242,173029,178213,1999,775,1224,2.57,48590
1110,오피스텔,2014 타경 21007,서울 도봉구 창동 629-25 8층 801호,37.643577,127.035521,건물 56.22㎡(17.01평) / 대지권 16.29㎡(4.93평),185000000,148000000,1.655000e+08,2015/03/16,...,173804,179437,351242,173029,178213,1999,775,1224,2.57,48590
1111,숙박시설,2014 타경 16357,서울 도봉구 쌍문동 31-15 1동,37.658802,127.038651,건물 209.63㎡(63.41평) / 토지 261㎡(78.95평) / 제시외 53.5 ㎡,808828920,517650000,5.250100e+08,2015/01/26,...,173804,179437,351242,173029,178213,1999,775,1224,2.57,48590

In [88]:
table_2015_2 = table_2015_1.merge(df3, on=['자치구'], how='inner')

table_2015_2

,building t,case num,address,Latitude,Longitude,size,appraiser,lowest,success,bid_date,...,한국인 여자,등록외국인 합계,등록외국인 남자,등록외국인 여자,세대당인구,65세이상고령자,지역내총생산(당해년가격),구성비,지역내총생산(2015년 기준년 연쇄가격),전년대비 증감률
0,오피스텔,2015 타경 12810,서울 강남구 대치동 889-47 비동 3층 317호,37.503835,127.050223,건물 38.71㎡(11.71평) / 대지권 7.75㎡(2.34평),202000000,161600000,1.911000e+08,2015/12/29,...,300070,5265,2784,2481,2.43,60330,62295492,16.8,62295492,5.3
1,종교시설,2015 타경 2677,서울 강남구 자곡동 288,37.479831,127.102842,건물 797.09㎡(241.12평) / 토지 655㎡(198.14평) / 제시외 1...,3872438950,3097951000,3.133300e+09,2015/12/24,...,300070,5265,2784,2481,2.43,60330,62295492,16.8,62295492,5.3
2,근린상가,2015 타경 4680,서울 강남구 논현동 108 논현웰스톤 1층 162호,37.518417,127.038003,건물 129.21㎡(39.09평) / 대지권 40.77㎡(12.33평),784000000,627200000,7.017000e+08,2015/12/24,...,300070,5265,2784,2481,2.43,60330,62295492,16.8,62295492,5.3
3,근린상가,2015 타경 1056,서울 강남구 역삼동 815 점프밀라노 9층 901호,37.501275,127.026641,건물 86.45㎡(26.15평) / 대지권 17.95㎡(5.43평),430000000,430000000,9.950000e+08,2015/11/26,...,300070,5265,2784,2481,2.43,60330,62295492,16.8,62295492,5.3
4,근린시설,2015 타경 2585,서울 강남구 청담동 7,37.523254,127.047221,건물 1369.19㎡(414.18평) / 토지 431.9㎡(130.65평) / 제시...,8358750000,8358750000,9.311000e+09,2015/10/14,...,300070,5265,2784,2481,2.43,60330,62295492,16.8,62295492,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107,근린상가,2014 타경 17879,서울 도봉구 창동 4 6층 1호,37.652865,127.049188,건물 307.59㎡(93.05평) / 대지권 91.98㎡(27.82평),703000000,562400000,6.010000e+08,2015/04/20,...,178213,1999,775,1224,2.57,48590,2906723,0.8,2906723,-2.0
1108,근린상가,2014 타경 18551,서울 도봉구 도봉동 81-1 상가동 지하 1층 9호,37.682475,127.049372,건물 10.73㎡(3.25평) / 대지권 7.65㎡(2.31평),13000000,6656000,NaN,2015/04/13,...,178213,1999,775,1224,2.57,48590,2906723,0.8,2906723,-2.0
1109,근린상가,2014 타경 18483,서울 도봉구 방학동 719-3 1층 108호,37.669193,127.045262,건물 23.89㎡(7.23평) / 대지권 7.1㎡(2.15평),145000000,116000000,1.171000e+08,2015/03/23,...,178213,1999,775,1224,2.57,48590,2906723,0.8,2906723,-2.0
1110,오피스텔,2014 타경 21007,서울 도봉구 창동 629-25 8층 801호,37.643577,127.035521,건물 56.22㎡(17.01평) / 대지권 16.29㎡(4.93평),185000000,148000000,1.655000e+08,2015/03/16,...,178213,1999,775,1224,2.57,48590,2906723,0.8,2906723,-2.0
1111,숙박시설,2014 타경 16357,서울 도봉구 쌍문동 31-15 1동,37.658802,127.038651,건물 209.63㎡(63.41평) / 토지 261㎡(78.95평) / 제시외 53.5 ㎡,808828920,517650000,5.250100e+08,2015/01/26,...,178213,1999,775,1224,2.57,48590,2906723,0.8,2906723,-2.0

In [89]:
table_2015_3 = table_2015_2.merge(df4, on=['자치구'], how='inner')

table_2015_3

,building t,case num,address,Latitude,Longitude,size,appraiser,lowest,success,bid_date,...,공공행정국방및사회보장행정,공공행정국방및사회보장행정 증감률,교육서비스업,교육서비스업 증감률,보건업 및 사회복지 서비스업,보건업 및 사회복지 서비스업 증감률,문화 및 기타서비스업,문화 및 기타서비스업 증감률,순생산물세,순생산물세 증감률
0,오피스텔,2015 타경 12810,서울 강남구 대치동 889-47 비동 3층 317호,37.503835,127.050223,건물 38.71㎡(11.71평) / 대지권 7.75㎡(2.34평),202000000,161600000,1.911000e+08,2015/12/29,...,275093,-16.1,1588177,0.0,2419185,6.4,1586264,-3.7,5429338,4.8
1,종교시설,2015 타경 2677,서울 강남구 자곡동 288,37.479831,127.102842,건물 797.09㎡(241.12평) / 토지 655㎡(198.14평) / 제시외 1...,3872438950,3097951000,3.133300e+09,2015/12/24,...,275093,-16.1,1588177,0.0,2419185,6.4,1586264,-3.7,5429338,4.8
2,근린상가,2015 타경 4680,서울 강남구 논현동 108 논현웰스톤 1층 162호,37.518417,127.038003,건물 129.21㎡(39.09평) / 대지권 40.77㎡(12.33평),784000000,627200000,7.017000e+08,2015/12/24,...,275093,-16.1,1588177,0.0,2419185,6.4,1586264,-3.7,5429338,4.8
3,근린상가,2015 타경 1056,서울 강남구 역삼동 815 점프밀라노 9층 901호,37.501275,127.026641,건물 86.45㎡(26.15평) / 대지권 17.95㎡(5.43평),430000000,430000000,9.950000e+08,2015/11/26,...,275093,-16.1,1588177,0.0,2419185,6.4,1586264,-3.7,5429338,4.8
4,근린시설,2015 타경 2585,서울 강남구 청담동 7,37.523254,127.047221,건물 1369.19㎡(414.18평) / 토지 431.9㎡(130.65평) / 제시...,8358750000,8358750000,9.311000e+09,2015/10/14,...,275093,-16.1,1588177,0.0,2419185,6.4,1586264,-3.7,5429338,4.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1107,근린상가,2014 타경 17879,서울 도봉구 창동 4 6층 1호,37.652865,127.049188,건물 307.59㎡(93.05평) / 대지권 91.98㎡(27.82평),703000000,562400000,6.010000e+08,2015/04/20,...,197330,-3.7,297742,-1.1,252351,7.5,181540,-6.1,217080,0.1
1108,근린상가,2014 타경 18551,서울 도봉구 도봉동 81-1 상가동 지하 1층 9호,37.682475,127.049372,건물 10.73㎡(3.25평) / 대지권 7.65㎡(2.31평),13000000,6656000,NaN,2015/04/13,...,197330,-3.7,297742,-1.1,252351,7.5,181540,-6.1,217080,0.1
1109,근린상가,2014 타경 18483,서울 도봉구 방학동 719-3 1층 108호,37.669193,127.045262,건물 23.89㎡(7.23평) / 대지권 7.1㎡(2.15평),145000000,116000000,1.171000e+08,2015/03/23,...,197330,-3.7,297742,-1.1,252351,7.5,181540,-6.1,217080,0.1
1110,오피스텔,2014 타경 21007,서울 도봉구 창동 629-25 8층 801호,37.643577,127.035521,건물 56.22㎡(17.01평) / 대지권 16.29㎡(4.93평),185000000,148000000,1.655000e+08,2015/03/16,...,197330,-3.7,297742,-1.1,252351,7.5,181540,-6.1,217080,0.1
1111,숙박시설,2014 타경 16357,서울 도봉구 쌍문동 31-15 1동,37.658802,127.038651,건물 209.63㎡(63.41평) / 토지 261㎡(78.95평) / 제시외 53.5 ㎡,808828920,517650000,5.250100e+08,2015/01/26,...,197330,-3.7,297742,-1.1,252351,7.5,181540,-6.1,217080,0.1

In [90]:
table_2015_3.columns

Index(['building t', 'case num', 'address', 'Latitude', 'Longitude', 'size',
       'appraiser', 'lowest', 'success', 'bid_date',
       ...
       '공공행정국방및사회보장행정', '공공행정국방및사회보장행정 증감률', '교육서비스업', '교육서비스업 증감률',
       '보건업 및 사회복지 서비스업', '보건업 및 사회복지 서비스업 증감률', '문화 및 기타서비스업 ',
       '문화 및 기타서비스업 증감률', '순생산물세', '순생산물세 증감률'],
      dtype='object', length=136)

In [92]:
table_2015_3.to_csv("/content/drive/MyDrive/기쁨코인/dataset/table/TABLE_2015.csv")

In [ ]:
# 2015 끝. 2016 2017에 대해서도 똑같이 해준다

In [100]:
path = "/content/drive/MyDrive/기쁨코인/dataset/table/table_2016.csv"
table_2016 = pd.read_csv(path).drop("Unnamed: 0", axis=1) 
df1 = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/인구밀도/2016 행정동별 인구밀도.xls")
pop_density = df1[df1['동']=='소계']
pop_density = pop_density.drop(['기간', '동'], axis=1).reset_index(drop=True)
pop_density
pop_num = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/인구/2015-2017 서울시 자치구별 주민등록인구.xls")
pop_num = pop_num.loc[pop_num['기간']==2016].reset_index(drop=True).drop(0, axis=0).drop(['기간', '계'], axis=1)
pop = pop_density.merge(pop_num, how='inner')
df2 = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/지역내 총생산/2016 지역내총생산.xls").drop("기간", axis=1)
df3 = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/자치구별 총 부가가치/2016 자치구별 총부가가치.xls")
df3 = df3.drop(['기간', '광업 ', '광업 증감률'], axis=1) # 결측치가 존재했었는데 NaN이 아니라 -, ... 이런식이었음
for i in range(len(table_2016)):
    table_2016.loc[i, '자치구'] = table_2016['address'][i].split()[1]
table_2016_1 = table_2016.merge(pop, on=['자치구'], how='inner')
table_2016_2 = table_2016_1.merge(df2, on=['자치구'], how='inner')
table_2016_3 = table_2016_2.merge(df3, on=['자치구'], how='inner')
table_2016_3.to_csv("/content/drive/MyDrive/기쁨코인/dataset/table/TABLE_2016.csv")

In [102]:
path = "/content/drive/MyDrive/기쁨코인/dataset/table/table_2017.csv"
table_2017 = pd.read_csv(path).drop("Unnamed: 0", axis=1) 
df1 = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/인구밀도/2017 행정동별 인구밀도.xls")
pop_density = df1[df1['동']=='소계']
pop_density = pop_density.drop(['기간', '동'], axis=1).reset_index(drop=True)
pop_density
pop_num = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/인구/2015-2017 서울시 자치구별 주민등록인구.xls")
pop_num = pop_num.loc[pop_num['기간']==2017].reset_index(drop=True).drop(0, axis=0).drop(['기간', '계'], axis=1)
pop = pop_density.merge(pop_num, how='inner')
df2 = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/지역내 총생산/2017 지역내총생산.xls").drop("기간", axis=1)
df3 = pd.read_excel("/content/drive/MyDrive/기쁨코인/dataset/X_attributes_final/자치구별 총 부가가치/2017 자치구별 총부가가치.xls")
df3 = df3.drop(['기간', '광업 ', '광업 증감률'], axis=1) 
for i in range(len(table_2017)):
    table_2017.loc[i, '자치구'] = table_2017['address'][i].split()[1]
table_2017_1 = table_2017.merge(pop, on=['자치구'], how='inner')
table_2017_2 = table_2017_1.merge(df2, on=['자치구'], how='inner')
table_2017_3 = table_2017_2.merge(df3, on=['자치구'], how='inner')
table_2017_3.to_csv("/content/drive/MyDrive/기쁨코인/dataset/table/TABLE_2017.csv")