In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [97]:
import pandas as pd

path_2 ='/content/drive/MyDrive/기쁨코인/dataset/X_attributes/음식점/음식점_2017.csv'
data = pd.read_csv(path_2, encoding='utf-8')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (20,25,26,28,29,30,31,37,39,40,42,43) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [98]:
data.columns

Index(['Unnamed: 0', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자', '영업상태코드', '영업상태명',
       '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자', '전화번호',
       '소재지면적', '소재지우편번호', '지번주소', '도로명주소', '도로명우편번호', '사업장명', '최종수정일자',
       '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)', '위생업태명', '남성종사자수',
       '여성종사자수', '영업장주변구분명', '등급구분명', '급수시설구분명', '총인원', '본사종업원수', '공장사무직종업원수',
       '공장판매직종업원수', '공장생산직종업원수', '건물소유구분명', '보증액', '월세액', '다중이용업소여부', '시설총규모',
       '전통업소지정번호', '전통업소주된음식', '홈페이지'],
      dtype='object')

In [99]:
data.head(10)

,Unnamed: 0,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,...,공장판매직종업원수,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지
0,0,3000000,3000000-101-1995-05829,19951111,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,725.98,NaN,NaN,NaN
1,1,3000000,3000000-101-2002-11872,20020206,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,286.07,NaN,NaN,NaN
2,2,3000000,3000000-101-1990-03102,19900531,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,23.12,NaN,NaN,NaN
3,3,3000000,3000000-101-1990-01952,19900605,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,17.04,NaN,NaN,NaN
4,4,3000000,3000000-101-1991-06486,19910702,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,47.82,NaN,NaN,NaN
5,5,3000000,3000000-101-1992-01249,19920109,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,87.61,NaN,NaN,NaN
6,6,3000000,3000000-101-1992-01722,19920109,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,43.25,NaN,NaN,NaN
7,7,3000000,3000000-101-1990-07003,19901027,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,28.80,NaN,NaN,NaN
8,39,3000000,3000000-101-1990-04697,19901031,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,169.54,NaN,NaN,NaN
9,40,3000000,3000000-101-1990-00664,19901102,NaN,1,영업/정상,1,영업,NaN,...,NaN,NaN,NaN,NaN,NaN,N,67.92,NaN,NaN,NaN

In [100]:
data=data.drop(['개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자', '영업상태코드', '영업상태명',
       '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자', '전화번호',
       '최종수정일자','데이터갱신구분', '데이터갱신일자','남성종사자수','여성종사자수'],axis=1)

In [101]:
data.head(20)

,Unnamed: 0,소재지면적,소재지우편번호,지번주소,도로명주소,도로명우편번호,사업장명,업태구분명,좌표정보(X),좌표정보(Y),...,공장판매직종업원수,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지
0,0,NaN,110846.0,서울특별시 종로구 평창동 110-1번지,서울특별시 종로구 평창길 352 (평창동),3004.0,북악파크부페,뷔페식,197993.205677,456584.627065144,...,NaN,NaN,NaN,NaN,NaN,N,725.98,NaN,NaN,NaN
1,1,NaN,110290.0,서울특별시 종로구 인사동 98번지,서울특별시 종로구 종로11길 10 12층 (인사동),3164.0,시민식당 2호점,한식,198681.571899,452050.274345174,...,NaN,NaN,NaN,NaN,NaN,N,286.07,NaN,NaN,NaN
2,2,NaN,110126.0,서울특별시 종로구 종로6가 129-1번지,서울특별시 종로구 종로41길 10 (종로6가),3124.0,일번우동,분식,200533.453584,452156.900282796,...,NaN,NaN,NaN,NaN,NaN,N,23.12,NaN,NaN,NaN
3,3,17.04,110043.0,서울특별시 종로구 통인동 27-2,서울특별시 종로구 필운대로6길 17-1 (통인동),3036.0,서촌소국밥,한식,197250.385438,453135.451266411,...,NaN,NaN,NaN,NaN,NaN,N,17.04,NaN,NaN,NaN
4,4,47.82,110843.0,서울특별시 종로구 창신동 696-1,서울특별시 종로구 종로 289 (창신동),3101.0,빽다방 동대문역점,기타,200811.925354,452162.569488435,...,NaN,NaN,NaN,NaN,NaN,N,47.82,NaN,NaN,NaN
5,5,NaN,110370.0,서울특별시 종로구 묘동 35-1번지,서울특별시 종로구 돈화문로8길 10 (묘동),3138.0,팔도식당,한식,199246.353827,452153.495899362,...,NaN,NaN,NaN,NaN,NaN,N,87.61,NaN,NaN,NaN
6,6,NaN,110090.0,서울특별시 종로구 교북동 90-1번지,서울특별시 종로구 통일로 184 (교북동),NaN,군산집,한식,196636.270703,451995.850942199,...,NaN,NaN,NaN,NaN,NaN,N,43.25,NaN,NaN,NaN
7,7,NaN,110862.0,서울특별시 종로구 숭인동 65-18번지 지상1층,서울특별시 종로구 지봉로 56 (숭인동지상1층),3113.0,올리브떡볶이(동묘점),한식,201334.426495,452522.963236492,...,NaN,NaN,NaN,NaN,NaN,N,28.80,NaN,NaN,NaN
8,39,169.54,110846.0,서울특별시 종로구 평창동 66-50 킴스관광호텔,서울특별시 종로구 평창문화로 136 킴스관광호텔 (평창동),3010.0,두레유,경양식,197733.391819,456346.84737021,...,NaN,NaN,NaN,NaN,NaN,N,169.54,NaN,NaN,NaN
9,40,NaN,110070.0,서울특별시 종로구 내수동 61-1번지,NaN,NaN,연정,한식,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,N,67.92,NaN,NaN,NaN
10,41,61.63,110320.0,서울특별시 종로구 낙원동 59-4번지 지상1층,서울특별시 종로구 삼일대로28길 12 (낙원동지상1층),3133.0,어심,기타,198927.266408,452352.097462562,...,NaN,NaN,NaN,NaN,NaN,N,61.63,NaN,NaN,NaN
11,42,NaN,110822.0,서울특별시 종로구 세종로 200-0번지,서울특별시 종로구 세종대로 161 (세종로),3183.0,애드,분식,197836.587371,452046.256276552,...,NaN,NaN,NaN,NaN,NaN,N,9.97,NaN,NaN,NaN
12,43,26.04,110071.0,서울특별시 종로구 당주동 160,서울특별시 종로구 새문안로5길 13 지하1층 7호 (당주동),3182.0,국시방,한식,197673.919715,452123.434528869,...,NaN,NaN,NaN,NaN,NaN,N,26.04,NaN,NaN,NaN
13,44,32.14,110845.0,서울특별시 종로구 충신동 73-3,서울특별시 종로구 율곡로 230-27 (충신동),3123.0,우미옥,한식,200285.462440,452595.765799752,...,0.0,0.0,NaN,0.0,0,N,32.14,NaN,NaN,NaN
14,45,NaN,110062.0,서울특별시 종로구 신문로2가 19-0번지,NaN,NaN,시인,경양식,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,N,23.00,NaN,NaN,NaN
15,46,138.19,110123.0,서울특별시 종로구 종로3가 132-1,서울특별시 종로구 수표로20길 43 (종로3가),3192.0,가르텐 비어,호프/통닭,199217.330754,451974.244323975,...,NaN,NaN,NaN,NaN,NaN,N,138.19,NaN,NaN,NaN
16,47,NaN,110812.0,서울특별시 종로구 명륜3가 53-0번지,NaN,NaN,명륜 쭈꾸미,한식,199554.074424,453721.462706742,...,NaN,NaN,NaN,NaN,NaN,N,37.10,NaN,NaN,NaN
17,48,50.84,110524.0,서울특별시 종로구 명륜4가 11-2,서울특별시 종로구 대명1길 4 (명륜4가),3078.0,파닭,호프/통닭,199997.520182,453440.271080169,...,0.0,0.0,NaN,0.0,0,N,50.84,NaN,NaN,NaN
18,49,NaN,110812.0,서울특별시 종로구 명륜3가 53-0번지,NaN,NaN,곰돌이,분식,199554.074424,453721.462706742,...,NaN,NaN,NaN,NaN,NaN,N,17.50,NaN,NaN,NaN
19,50,NaN,110809.0,서울특별시 종로구 동숭동 1-105번지 지하동 1층호,서울특별시 종로구 대학로10길 16 지하동 1층호 (동숭동),3086.0,홍콩반점 0410,한식,200202.422227,453256.751921498,...,NaN,NaN,NaN,NaN,NaN,N,177.13,NaN,NaN,NaN

In [102]:
data=data.drop(['등급구분명','급수시설구분명','총인원','본사종업원수','공장사무직종업원수','공장판매직종업원수','공장생산직종업원수','건물소유구분명','보증액','월세액','다중이용업소여부'],axis=1)

In [103]:
data.columns

Index(['Unnamed: 0', '소재지면적', '소재지우편번호', '지번주소', '도로명주소', '도로명우편번호', '사업장명',
       '업태구분명', '좌표정보(X)', '좌표정보(Y)', '위생업태명', '영업장주변구분명', '시설총규모', '전통업소지정번호',
       '전통업소주된음식', '홈페이지'],
      dtype='object')

In [104]:
data.head(10)

,Unnamed: 0,소재지면적,소재지우편번호,지번주소,도로명주소,도로명우편번호,사업장명,업태구분명,좌표정보(X),좌표정보(Y),위생업태명,영업장주변구분명,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지
0,0,NaN,110846.0,서울특별시 종로구 평창동 110-1번지,서울특별시 종로구 평창길 352 (평창동),3004.0,북악파크부페,뷔페식,197993.205677,456584.627065144,뷔페식,기타,725.98,NaN,NaN,NaN
1,1,NaN,110290.0,서울특별시 종로구 인사동 98번지,서울특별시 종로구 종로11길 10 12층 (인사동),3164.0,시민식당 2호점,한식,198681.571899,452050.274345174,한식,NaN,286.07,NaN,NaN,NaN
2,2,NaN,110126.0,서울특별시 종로구 종로6가 129-1번지,서울특별시 종로구 종로41길 10 (종로6가),3124.0,일번우동,분식,200533.453584,452156.900282796,분식,기타,23.12,NaN,NaN,NaN
3,3,17.04,110043.0,서울특별시 종로구 통인동 27-2,서울특별시 종로구 필운대로6길 17-1 (통인동),3036.0,서촌소국밥,한식,197250.385438,453135.451266411,한식,기타,17.04,NaN,NaN,NaN
4,4,47.82,110843.0,서울특별시 종로구 창신동 696-1,서울특별시 종로구 종로 289 (창신동),3101.0,빽다방 동대문역점,기타,200811.925354,452162.569488435,기타,기타,47.82,NaN,NaN,NaN
5,5,NaN,110370.0,서울특별시 종로구 묘동 35-1번지,서울특별시 종로구 돈화문로8길 10 (묘동),3138.0,팔도식당,한식,199246.353827,452153.495899362,한식,기타,87.61,NaN,NaN,NaN
6,6,NaN,110090.0,서울특별시 종로구 교북동 90-1번지,서울특별시 종로구 통일로 184 (교북동),NaN,군산집,한식,196636.270703,451995.850942199,한식,기타,43.25,NaN,NaN,NaN
7,7,NaN,110862.0,서울특별시 종로구 숭인동 65-18번지 지상1층,서울특별시 종로구 지봉로 56 (숭인동지상1층),3113.0,올리브떡볶이(동묘점),한식,201334.426495,452522.963236492,한식,주택가주변,28.80,NaN,NaN,NaN
8,39,169.54,110846.0,서울특별시 종로구 평창동 66-50 킴스관광호텔,서울특별시 종로구 평창문화로 136 킴스관광호텔 (평창동),3010.0,두레유,경양식,197733.391819,456346.84737021,경양식,기타,169.54,NaN,NaN,NaN
9,40,NaN,110070.0,서울특별시 종로구 내수동 61-1번지,NaN,NaN,연정,한식,NaN,NaN,한식,아파트지역,67.92,NaN,NaN,NaN

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132721 entries, 0 to 132720
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  132721 non-null  int64
 1   소재지면적       126049 non-null  float64
 2   소재지우편번호     132533 non-null  float64
 3   지번주소        132534 non-null  object
 4   도로명주소       130178 non-null  object
 5   도로명우편번호     128266 non-null  float64
 6   사업장명        132721 non-null  object
 7   업태구분명       132708 non-null  object
 8   좌표정보(X)     131525 non-null  float64
 9   좌표정보(Y)     131524 non-null  object
 10  위생업태명       130637 non-null  object
 11  영업장주변구분명    41697 non-null   object
 12  시설총규모       130646 non-null  float64
 13  전통업소지정번호    89 non-null      object
 14  전통업소주된음식    48 non-null      object
 15  홈페이지        0 non-null       float64
dtypes: float64(6), int64(1), object(9)
memory usage: 16.2+ MB

In [106]:
data.isnull().sum()

Unnamed: 0         0
소재지면적           6672
소재지우편번호          188
지번주소             187
도로명주소           2543
도로명우편번호         4455
사업장명               0
업태구분명             13
좌표정보(X)         1196
좌표정보(Y)         1197
위생업태명           2084
영업장주변구분명       91024
시설총규모           2075
전통업소지정번호      132632
전통업소주된음식      132673
홈페이지          132721
dtype: int64

In [107]:
data=data.dropna(subset = ["좌표정보(Y)"])

In [108]:
data.head(10)

,Unnamed: 0,소재지면적,소재지우편번호,지번주소,도로명주소,도로명우편번호,사업장명,업태구분명,좌표정보(X),좌표정보(Y),위생업태명,영업장주변구분명,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지
0,0,NaN,110846.0,서울특별시 종로구 평창동 110-1번지,서울특별시 종로구 평창길 352 (평창동),3004.0,북악파크부페,뷔페식,197993.205677,456584.627065144,뷔페식,기타,725.98,NaN,NaN,NaN
1,1,NaN,110290.0,서울특별시 종로구 인사동 98번지,서울특별시 종로구 종로11길 10 12층 (인사동),3164.0,시민식당 2호점,한식,198681.571899,452050.274345174,한식,NaN,286.07,NaN,NaN,NaN
2,2,NaN,110126.0,서울특별시 종로구 종로6가 129-1번지,서울특별시 종로구 종로41길 10 (종로6가),3124.0,일번우동,분식,200533.453584,452156.900282796,분식,기타,23.12,NaN,NaN,NaN
3,3,17.04,110043.0,서울특별시 종로구 통인동 27-2,서울특별시 종로구 필운대로6길 17-1 (통인동),3036.0,서촌소국밥,한식,197250.385438,453135.451266411,한식,기타,17.04,NaN,NaN,NaN
4,4,47.82,110843.0,서울특별시 종로구 창신동 696-1,서울특별시 종로구 종로 289 (창신동),3101.0,빽다방 동대문역점,기타,200811.925354,452162.569488435,기타,기타,47.82,NaN,NaN,NaN
5,5,NaN,110370.0,서울특별시 종로구 묘동 35-1번지,서울특별시 종로구 돈화문로8길 10 (묘동),3138.0,팔도식당,한식,199246.353827,452153.495899362,한식,기타,87.61,NaN,NaN,NaN
6,6,NaN,110090.0,서울특별시 종로구 교북동 90-1번지,서울특별시 종로구 통일로 184 (교북동),NaN,군산집,한식,196636.270703,451995.850942199,한식,기타,43.25,NaN,NaN,NaN
7,7,NaN,110862.0,서울특별시 종로구 숭인동 65-18번지 지상1층,서울특별시 종로구 지봉로 56 (숭인동지상1층),3113.0,올리브떡볶이(동묘점),한식,201334.426495,452522.963236492,한식,주택가주변,28.80,NaN,NaN,NaN
8,39,169.54,110846.0,서울특별시 종로구 평창동 66-50 킴스관광호텔,서울특별시 종로구 평창문화로 136 킴스관광호텔 (평창동),3010.0,두레유,경양식,197733.391819,456346.84737021,경양식,기타,169.54,NaN,NaN,NaN
10,41,61.63,110320.0,서울특별시 종로구 낙원동 59-4번지 지상1층,서울특별시 종로구 삼일대로28길 12 (낙원동지상1층),3133.0,어심,기타,198927.266408,452352.097462562,기타,기타,61.63,NaN,NaN,NaN

In [109]:
data=data.drop(["영업장주변구분명","시설총규모","전통업소지정번호","전통업소주된음식","홈페이지"],axis=1)

In [110]:
data.isnull().sum()

Unnamed: 0       0
소재지면적         6417
소재지우편번호        187
지번주소           186
도로명주소         1459
도로명우편번호       3319
사업장명             0
업태구분명           13
좌표정보(X)          0
좌표정보(Y)          0
위생업태명         2074
dtype: int64

In [111]:
data.head(10)

,Unnamed: 0,소재지면적,소재지우편번호,지번주소,도로명주소,도로명우편번호,사업장명,업태구분명,좌표정보(X),좌표정보(Y),위생업태명
0,0,NaN,110846.0,서울특별시 종로구 평창동 110-1번지,서울특별시 종로구 평창길 352 (평창동),3004.0,북악파크부페,뷔페식,197993.205677,456584.627065144,뷔페식
1,1,NaN,110290.0,서울특별시 종로구 인사동 98번지,서울특별시 종로구 종로11길 10 12층 (인사동),3164.0,시민식당 2호점,한식,198681.571899,452050.274345174,한식
2,2,NaN,110126.0,서울특별시 종로구 종로6가 129-1번지,서울특별시 종로구 종로41길 10 (종로6가),3124.0,일번우동,분식,200533.453584,452156.900282796,분식
3,3,17.04,110043.0,서울특별시 종로구 통인동 27-2,서울특별시 종로구 필운대로6길 17-1 (통인동),3036.0,서촌소국밥,한식,197250.385438,453135.451266411,한식
4,4,47.82,110843.0,서울특별시 종로구 창신동 696-1,서울특별시 종로구 종로 289 (창신동),3101.0,빽다방 동대문역점,기타,200811.925354,452162.569488435,기타
5,5,NaN,110370.0,서울특별시 종로구 묘동 35-1번지,서울특별시 종로구 돈화문로8길 10 (묘동),3138.0,팔도식당,한식,199246.353827,452153.495899362,한식
6,6,NaN,110090.0,서울특별시 종로구 교북동 90-1번지,서울특별시 종로구 통일로 184 (교북동),NaN,군산집,한식,196636.270703,451995.850942199,한식
7,7,NaN,110862.0,서울특별시 종로구 숭인동 65-18번지 지상1층,서울특별시 종로구 지봉로 56 (숭인동지상1층),3113.0,올리브떡볶이(동묘점),한식,201334.426495,452522.963236492,한식
8,39,169.54,110846.0,서울특별시 종로구 평창동 66-50 킴스관광호텔,서울특별시 종로구 평창문화로 136 킴스관광호텔 (평창동),3010.0,두레유,경양식,197733.391819,456346.84737021,경양식
10,41,61.63,110320.0,서울특별시 종로구 낙원동 59-4번지 지상1층,서울특별시 종로구 삼일대로28길 12 (낙원동지상1층),3133.0,어심,기타,198927.266408,452352.097462562,기타

In [112]:
data=data.drop(["소재지면적","소재지우편번호"],axis=1)

In [113]:
data=data.astype({"좌표정보(Y)":float})

ValueError: ignored

In [114]:
idx=data[data["좌표정보(Y)"]=="기타"].index
data.drop(idx,inplace=True)

In [115]:
data.head(10)

,Unnamed: 0,지번주소,도로명주소,도로명우편번호,사업장명,업태구분명,좌표정보(X),좌표정보(Y),위생업태명
0,0,서울특별시 종로구 평창동 110-1번지,서울특별시 종로구 평창길 352 (평창동),3004.0,북악파크부페,뷔페식,197993.205677,456584.627065144,뷔페식
1,1,서울특별시 종로구 인사동 98번지,서울특별시 종로구 종로11길 10 12층 (인사동),3164.0,시민식당 2호점,한식,198681.571899,452050.274345174,한식
2,2,서울특별시 종로구 종로6가 129-1번지,서울특별시 종로구 종로41길 10 (종로6가),3124.0,일번우동,분식,200533.453584,452156.900282796,분식
3,3,서울특별시 종로구 통인동 27-2,서울특별시 종로구 필운대로6길 17-1 (통인동),3036.0,서촌소국밥,한식,197250.385438,453135.451266411,한식
4,4,서울특별시 종로구 창신동 696-1,서울특별시 종로구 종로 289 (창신동),3101.0,빽다방 동대문역점,기타,200811.925354,452162.569488435,기타
5,5,서울특별시 종로구 묘동 35-1번지,서울특별시 종로구 돈화문로8길 10 (묘동),3138.0,팔도식당,한식,199246.353827,452153.495899362,한식
6,6,서울특별시 종로구 교북동 90-1번지,서울특별시 종로구 통일로 184 (교북동),NaN,군산집,한식,196636.270703,451995.850942199,한식
7,7,서울특별시 종로구 숭인동 65-18번지 지상1층,서울특별시 종로구 지봉로 56 (숭인동지상1층),3113.0,올리브떡볶이(동묘점),한식,201334.426495,452522.963236492,한식
8,39,서울특별시 종로구 평창동 66-50 킴스관광호텔,서울특별시 종로구 평창문화로 136 킴스관광호텔 (평창동),3010.0,두레유,경양식,197733.391819,456346.84737021,경양식
10,41,서울특별시 종로구 낙원동 59-4번지 지상1층,서울특별시 종로구 삼일대로28길 12 (낙원동지상1층),3133.0,어심,기타,198927.266408,452352.097462562,기타

In [116]:
data[data['좌표정보(Y)']=="기타"]

Empty DataFrame
Columns: [Unnamed: 0, 지번주소, 도로명주소, 도로명우편번호, 사업장명, 업태구분명, 좌표정보(X), 좌표정보(Y), 위생업태명]
Index: []

In [117]:
data[data['좌표정보(Y)']=="분식"]

Empty DataFrame
Columns: [Unnamed: 0, 지번주소, 도로명주소, 도로명우편번호, 사업장명, 업태구분명, 좌표정보(X), 좌표정보(Y), 위생업태명]
Index: []

In [72]:
idx=data[data["좌표정보(Y)"]=="분식"].index
data.drop(idx,inplace=True)

In [118]:
data["좌표정보(Y)"] = data["좌표정보(Y)"].astype(float)

ValueError: ignored

In [119]:
idx=data[data["좌표정보(Y)"]=="일식"].index
data.drop(idx,inplace=True)

In [120]:
data["좌표정보(Y)"] = data["좌표정보(Y)"].astype(float)

ValueError: ignored

In [121]:
idx=data[data["좌표정보(Y)"]=="한식"].index
data.drop(idx,inplace=True)

In [122]:
data["좌표정보(Y)"] = data["좌표정보(Y)"].astype(float)

In [78]:
idx=data[data["좌표정보(Y)"]=="중국식"].index
data.drop(idx,inplace=True)

In [79]:
data["좌표정보(Y)"] = data["좌표정보(Y)"].astype(float)

In [123]:
# 변환성공
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 131514 entries, 0 to 132720
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  131514 non-null  int64
 1   지번주소        131328 non-null  object
 2   도로명주소       130055 non-null  object
 3   도로명우편번호     128195 non-null  float64
 4   사업장명        131514 non-null  object
 5   업태구분명       131501 non-null  object
 6   좌표정보(X)     131514 non-null  float64
 7   좌표정보(Y)     131514 non-null  float64
 8   위생업태명       129446 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 10.0+ MB

In [30]:
pip install pyproj

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyproj
  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 7.7 MB/s
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from pyproj) (2022.5.18.1)
Installing collected packages: pyproj
Successfully installed pyproj-3.2.1

In [81]:
import pyproj
import folium
import numpy as np

In [124]:
data_location=data.copy()

In [125]:
data_location.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 131514 entries, 0 to 132720
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  131514 non-null  int64
 1   지번주소        131328 non-null  object
 2   도로명주소       130055 non-null  object
 3   도로명우편번호     128195 non-null  float64
 4   사업장명        131514 non-null  object
 5   업태구분명       131501 non-null  object
 6   좌표정보(X)     131514 non-null  float64
 7   좌표정보(Y)     131514 non-null  float64
 8   위생업태명       129446 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 10.0+ MB

In [126]:
data_location.columns

Index(['Unnamed: 0', '지번주소', '도로명주소', '도로명우편번호', '사업장명', '업태구분명', '좌표정보(X)',
       '좌표정보(Y)', '위생업태명'],
      dtype='object')

In [129]:
data_location=data_location.drop(['Unnamed: 0', '지번주소', '도로명주소', '도로명우편번호', '사업장명','업태구분명','위생업태명'],axis=1)

In [130]:
def project_array(coord,p1_type,p2_type):
  p1=pyproj.Proj(init=p1_type)
  p2=pyproj.Proj(init=p2_type)
  fx,fy=pyproj.transform(p1,p2,coord[:,0],coord[:,1])
  return np.dstack([fx,fy])[0]
  
coord=np.array(data_location)

In [131]:
coord

array([[197993.20567742, 456584.62706514],
       [198681.57189916, 452050.27434517],
       [200533.45358427, 452156.9002828 ],
       ...,
       [206636.22592589, 449204.92327488],
       [193658.47398104, 446413.91770955],
       [189228.86148312, 442032.8002303 ]])

In [132]:
p1_type="epsg:2097"
p2_type="epsg:4326"

result=project_array(coord, p1_type, p2_type)
result

/usr/local/lib/python3.7/dist-packages/pyproj/crs/crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
/usr/local/lib/python3.7/dist-packages/pyproj/crs/crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  after removing the cwd from sys.path.

array([[126.97516899,  37.61159224],
       [126.98297381,  37.5707397 ],
       [127.00393636,  37.57170131],
       ...,
       [127.07299146,  37.545081  ],
       [126.92616376,  37.5199354 ],
       [126.87612111,  37.48042032]])

In [133]:
data_location["longitude"]=result[:,0]
data_location["latitude"]=result[:,1]

In [90]:
#data_location.head(20)

In [134]:
data_location=data_location.drop(["좌표정보(X)","좌표정보(Y)"],axis=1)
data=data.drop(["좌표정보(X)","좌표정보(Y)"],axis=1)

In [135]:
#data_location.columns
#data.columns

In [136]:
data=pd.concat([data,data_location],axis=1)

In [94]:
#data.columns

In [137]:
data.head(20)

,Unnamed: 0,지번주소,도로명주소,도로명우편번호,사업장명,업태구분명,위생업태명,longitude,latitude
0,0,서울특별시 종로구 평창동 110-1번지,서울특별시 종로구 평창길 352 (평창동),3004.0,북악파크부페,뷔페식,뷔페식,126.975169,37.611592
1,1,서울특별시 종로구 인사동 98번지,서울특별시 종로구 종로11길 10 12층 (인사동),3164.0,시민식당 2호점,한식,한식,126.982974,37.570740
2,2,서울특별시 종로구 종로6가 129-1번지,서울특별시 종로구 종로41길 10 (종로6가),3124.0,일번우동,분식,분식,127.003936,37.571701
3,3,서울특별시 종로구 통인동 27-2,서울특별시 종로구 필운대로6길 17-1 (통인동),3036.0,서촌소국밥,한식,한식,126.966769,37.580514
4,4,서울특별시 종로구 창신동 696-1,서울특별시 종로구 종로 289 (창신동),3101.0,빽다방 동대문역점,기타,기타,127.007089,37.571752
5,5,서울특별시 종로구 묘동 35-1번지,서울특별시 종로구 돈화문로8길 10 (묘동),3138.0,팔도식당,한식,한식,126.989367,37.571670
6,6,서울특별시 종로구 교북동 90-1번지,서울특별시 종로구 통일로 184 (교북동),NaN,군산집,한식,한식,126.959822,37.570244
7,7,서울특별시 종로구 숭인동 65-18번지 지상1층,서울특별시 종로구 지봉로 56 (숭인동지상1층),3113.0,올리브떡볶이(동묘점),한식,한식,127.013004,37.574999
8,39,서울특별시 종로구 평창동 66-50 킴스관광호텔,서울특별시 종로구 평창문화로 136 킴스관광호텔 (평창동),3010.0,두레유,경양식,경양식,126.972227,37.609449
10,41,서울특별시 종로구 낙원동 59-4번지 지상1층,서울특별시 종로구 삼일대로28길 12 (낙원동지상1층),3133.0,어심,기타,기타,126.985754,37.573459
11,42,서울특별시 종로구 세종로 200-0번지,서울특별시 종로구 세종대로 161 (세종로),3183.0,애드,분식,분식,126.973409,37.570702
12,43,서울특별시 종로구 당주동 160,서울특별시 종로구 새문안로5길 13 지하1층 7호 (당주동),3182.0,국시방,한식,한식,126.971567,37.571397
13,44,서울특별시 종로구 충신동 73-3,서울특별시 종로구 율곡로 230-27 (충신동),3123.0,우미옥,한식,한식,127.001129,37.575656
15,46,서울특별시 종로구 종로3가 132-1,서울특별시 종로구 수표로20길 43 (종로3가),3192.0,가르텐 비어,호프/통닭,호프/통닭,126.989038,37.570055
16,47,서울특별시 종로구 명륜3가 53-0번지,NaN,NaN,명륜 쭈꾸미,한식,한식,126.992849,37.585798
17,48,서울특별시 종로구 명륜4가 11-2,서울특별시 종로구 대명1길 4 (명륜4가),3078.0,파닭,호프/통닭,호프/통닭,126.997870,37.583264
18,49,서울특별시 종로구 명륜3가 53-0번지,NaN,NaN,곰돌이,분식,분식,126.992849,37.585798
19,50,서울특별시 종로구 동숭동 1-105번지 지하동 1층호,서울특별시 종로구 대학로10길 16 지하동 1층호 (동숭동),3086.0,홍콩반점 0410,한식,한식,127.000189,37.581611
20,51,서울특별시 종로구 운니동 98-62번지,서울특별시 종로구 율곡로6길 22-1 1층 (운니동),3131.0,미성,한식,한식,126.986246,37.576397
21,52,서울특별시 종로구 연건동 190-10번지,서울특별시 종로구 대학로 48-11 (연건동),3122.0,효제,한식,한식,126.999651,37.575715

In [138]:
# 이름 수정해서 저장
data.to_csv('/content/drive/MyDrive/기쁨코인/dataset/X_attributes_modify/음식점_2017.csv', encoding='utf-8')